// This file was automatically generated. Don't edit it directly!
#![no_std]
#[cfg(feature = "a53-cti-0")]
pub mod a53_cti_0;
#[cfg(feature = "a53-cti-1")]
pub mod a53_cti_1;
#[cfg(feature = "a53-cti-2")]
pub mod a53_cti_2;
#[cfg(feature = "a53-cti-3")]
pub mod a53_cti_3;
#[cfg(feature = "a53-dbg-0")]
pub mod a53_dbg_0;
#[cfg(feature = "a53-dbg-1")]
pub mod a53_dbg_1;
#[cfg(feature = "a53-dbg-2")]
pub mod a53_dbg_2;
#[cfg(feature = "a53-dbg-3")]
pub mod a53_dbg_3;
#[cfg(feature = "a53-etm-0")]
pub mod a53_etm_0;
#[cfg(feature = "a53-etm-1")]
pub mod a53_etm_1;
#[cfg(feature = "a53-etm-2")]
pub mod a53_etm_2;
#[cfg(feature = "a53-etm-3")]
pub mod a53_etm_3;
#[cfg(feature = "a53-pmu-0")]
pub mod a53_pmu_0;
#[cfg(feature = "a53-pmu-1")]
pub mod a53_pmu_1;
#[cfg(feature = "a53-pmu-2")]
pub mod a53_pmu_2;
#[cfg(feature = "a53-pmu-3")]
pub mod a53_pmu_3;
#[cfg(feature = "a53-rom")]
pub mod a53_rom;
#[cfg(feature = "afifm")]
pub mod afifm;
#[cfg(feature = "ams")]
pub mod ams;
#[cfg(feature = "apm")]
pub mod apm;
#[cfg(feature = "apmddr")]
pub mod apmddr;
#[cfg(feature = "apu")]
pub mod apu;
#[cfg(feature = "axipcie-dma")]
pub mod axipcie_dma;
#[cfg(feature = "axipcie-egress")]
pub mod axipcie_egress;
#[cfg(feature = "axipcie-ingress")]
pub mod axipcie_ingress;
#[cfg(feature = "axipcie-main")]
pub mod axipcie_main;
#[cfg(feature = "bbram")]
pub mod bbram;
#[cfg(feature = "can")]
pub mod can;
#[cfg(feature = "cci400")]
pub mod cci400;
#[cfg(feature = "cci-reg")]
pub mod cci_reg;
#[cfg(feature = "crf-apb")]
pub mod crf_apb;
#[cfg(feature = "crl-apb")]
pub mod crl_apb;
#[cfg(feature = "csu")]
pub mod csu;
#[cfg(feature = "csudma")]
pub mod csudma;
#[cfg(feature = "cti")]
pub mod cti;
#[cfg(feature = "daprom")]
pub mod daprom;
#[cfg(feature = "ddr-phy")]
pub mod ddr_phy;
#[cfg(feature = "ddr-qos-ctrl")]
pub mod ddr_qos_ctrl;
#[cfg(feature = "ddrc")]
pub mod ddrc;
#[cfg(feature = "display-port")]
pub mod display_port;
#[cfg(feature = "dpdma")]
pub mod dpdma;
#[cfg(feature = "efuse")]
pub mod efuse;
#[cfg(feature = "etf4k")]
pub mod etf4k;
#[cfg(feature = "etf8k")]
pub mod etf8k;
#[cfg(feature = "etr")]
pub mod etr;
#[cfg(feature = "fpd-gpv")]
pub mod fpd_gpv;
#[cfg(feature = "fpd-slcr")]
pub mod fpd_slcr;
#[cfg(feature = "fpd-slcr-secure")]
pub mod fpd_slcr_secure;
#[cfg(feature = "ftm")]
pub mod ftm;
#[cfg(feature = "funnel3p")]
pub mod funnel3p;
#[cfg(feature = "funnel4p")]
pub mod funnel4p;
#[cfg(feature = "gem")]
pub mod gem;
#[cfg(feature = "gic400")]
pub mod gic400;
#[cfg(feature = "gpio")]
pub mod gpio;
#[cfg(feature = "gpu")]
pub mod gpu;
#[cfg(feature = "i2c")]
pub mod i2c;
#[cfg(feature = "iou-gpv")]
pub mod iou_gpv;
#[cfg(feature = "iou-scntr")]
pub mod iou_scntr;
#[cfg(feature = "iou-scntrs")]
pub mod iou_scntrs;
#[cfg(feature = "iou-secure-slcr")]
pub mod iou_secure_slcr;
#[cfg(feature = "iou-slcr")]
pub mod iou_slcr;
#[cfg(feature = "ipi")]
pub mod ipi;
#[cfg(feature = "lpd-gpv")]
pub mod lpd_gpv;
#[cfg(feature = "lpd-slcr")]
pub mod lpd_slcr;
#[cfg(feature = "lpd-slcr-secure")]
pub mod lpd_slcr_secure;
#[cfg(feature = "nand")]
pub mod nand;
#[cfg(feature = "ocm")]
pub mod ocm;
#[cfg(feature = "pcie-attrib")]
pub mod pcie_attrib;
#[cfg(feature = "pl390")]
pub mod pl390;
#[cfg(feature = "plsysmon")]
pub mod plsysmon;
#[cfg(feature = "pmu-global")]
pub mod pmu_global;
#[cfg(feature = "pmu-iomodule")]
pub mod pmu_iomodule;
#[cfg(feature = "pmu-lmb-bram")]
pub mod pmu_lmb_bram;
#[cfg(feature = "pmu-local")]
pub mod pmu_local;
#[cfg(feature = "pssysmon")]
pub mod pssysmon;
#[cfg(feature = "qspi")]
pub mod qspi;
#[cfg(feature = "r5-dbg-0")]
pub mod r5_dbg_0;
#[cfg(feature = "r5-dbg-1")]
pub mod r5_dbg_1;
#[cfg(feature = "r5-etm-0")]
pub mod r5_etm_0;
#[cfg(feature = "r5-etm-1")]
pub mod r5_etm_1;
#[cfg(feature = "r5-rom")]
pub mod r5_rom;
#[cfg(feature = "replic")]
pub mod replic;
#[cfg(feature = "rpu")]
pub mod rpu;
#[cfg(feature = "rsa")]
pub mod rsa;
#[cfg(feature = "rsa-core")]
pub mod rsa_core;
#[cfg(feature = "rtc")]
pub mod rtc;
#[cfg(feature = "sata-ahci-hba")]
pub mod sata_ahci_hba;
#[cfg(feature = "sata-ahci-portcntrl")]
pub mod sata_ahci_portcntrl;
#[cfg(feature = "sata-ahci-vendor")]
pub mod sata_ahci_vendor;
#[cfg(feature = "sdio")]
pub mod sdio;
#[cfg(feature = "serdes")]
pub mod serdes;
#[cfg(feature = "siou")]
pub mod siou;
#[cfg(feature = "smmu500")]
pub mod smmu500;
#[cfg(feature = "smmu-reg")]
pub mod smmu_reg;
#[cfg(feature = "spi")]
pub mod spi;
#[cfg(feature = "stm")]
pub mod stm;
#[cfg(feature = "swdt")]
pub mod swdt;
#[cfg(feature = "tpiu")]
pub mod tpiu;
#[cfg(feature = "tsgen")]
pub mod tsgen;
#[cfg(feature = "ttc")]
pub mod ttc;
#[cfg(feature = "uart")]
pub mod uart;
#[cfg(feature = "usb3-regs")]
pub mod usb3_regs;
#[cfg(feature = "usb3-xhci")]
pub mod usb3_xhci;
#[cfg(feature = "vcu-dec-top")]
pub mod vcu_dec_top;
#[cfg(feature = "vcu-enc-top")]
pub mod vcu_enc_top;
#[cfg(feature = "vcu-slcr")]
pub mod vcu_slcr;
#[cfg(feature = "xmpu-ddr")]
pub mod xmpu_ddr;
#[cfg(feature = "xmpu-fpd")]
pub mod xmpu_fpd;
#[cfg(feature = "xmpu-ocm")]
pub mod xmpu_ocm;
#[cfg(feature = "xmpu-sink")]
pub mod xmpu_sink;
#[cfg(feature = "xppu")]
pub mod xppu;
#[cfg(feature = "xppu-sink")]
pub mod xppu_sink;
#[cfg(feature = "zdma")]
pub mod zdma;
